language: perl

perl:
   - "blead"
   - "5.20"
   - "5.18"
   - "5.16"
   - "5.14"
   - "5.12"
   - "5.10"

before_install:
   - git clone git://github.com/haarg/perl-travis-helper
   - source perl-travis-helper/init
   - build-perl
   - perl -V
   - export AUTOMATED_TESTING=1 HARNESS_OPTIONS=j10:c HARNESS_TIMER=1 SKIP_POD_LINKCHECK=1
   - git submodule update --init --recursive

install:
   - cpanm --quiet --notest --skip-satisfied Dist::Zilla~5 Dist::Zilla::Plugin::PodWeaver Dist::Zilla::PluginBundle::ROKR Pod::Coverage::Moose Pod::Weaver::Section::Contributors Test::NoTabs Test::Spelling
   - git clone --branch=master git://github.com/maxmind/MaxMind-DB-Common-perl.git common
   - cd common
   - "dzil authordeps --missing | xargs -n 5 -P 10 cpanm --quiet --notest"
   - "dzil listdeps --missing  | grep -v MaxMind::DB | cpanm --quiet --notest"
   - dzil install --install-command "cpanm --quiet --notest ."
   - cd ..
   - "dzil authordeps --missing | xargs -n 5 -P 10 cpanm --quiet --notest"
   - "dzil listdeps --missing | grep -v MaxMind::DB | cpanm --quiet --notest"

script:
   - dzil test --release

notifications:
  email:
    recipients:
      - dev@maxmind.com
    on_success: change
    on_failure: always

