language: perl

perl:
  - "blead"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

before_install:
  - git submodule update --init --recursive
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR

install:
  - cpan-install --deps

script:
  - prove -l -j$((SYSTEM_CORES + 1)) $(test-dirs)

notifications:
  email:
    recipients:
      - dev@maxmind.com
    on_success: change
    on_failure: always

